---
name: "grow"
author: "Jonathan Strickland"

dependencies:
  - base
  - shake
  - aeson
  - text
  - bytestring
  - directory

executables:
  grow:
    source-dirs:
      - grow
    ghc-options:
      - -main-is
      - Grow
    main: Grow.hs
